server:
  port: 8081
spring:
  application:
    name: "neo4j-ollama"
  ai:
    ollama:
      base-url: "http://localhost:11434"
      embedding:
        enabled: true
        model: qwen2.5
      chat:
        enabled: true
        model: qwen2.5
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: your_password