server:
  port: 8081
spring:
  application:
    name: "mcp-ollama-client"
  ai:
    ollama:
      base-url: "http://localhost:11434"
      embedding:
        enabled: true
        model: qwen2.5
      chat:
        enabled: true
        model: qwen2.5