server:
  port: 8081
spring:
  application:
    name: "etl"
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  ai:
    ollama:
      base-url: "http://localhost:11434"
      embedding:
        enabled: true
        model: qwen2.5
      chat:
        enabled: true
        model: qwen2.5
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: etl-dev
        initialize-schema: true
logging:
  level:
    org.springframework.web: INFO
    com.sandy.etl: DEBUG
    org.apache.tika: INFO