server:
  port: 8081
spring:
  application:
    name: "chat-deepsek"
  thymeleaf:
    cache: false
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      base-url: ${SPRING_AI_OPENAI_BASE_URL}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_CHAT_MODEL}
          temperature: 0.7